// packages/examples/vue/components/observe-image/default.vue
<template>
  <div class="observe-image-container">
    <div class="scroll-wrapper" ref="scroll">
      <div class="scroll-content">
        <img width="100%" v-for="(url, index) in images" :src="url" alt="" :key="index">
      </div>
    </div>
  </div>
</template>

<script type="text/ecmascript-6">
  import BScroll from '@better-scroll/core'
  import ObserveImage from '@better-scroll/observe-image'

  BScroll.use(ObserveImage)
  export default {
    data () {
      return {
        images: [
          'https://dpubstatic.udache.com/static/dpubimg/dEswI1MVy6/zoo.png',
          'https://dpubstatic.udache.com/static/dpubimg/BYb_wPak21/home.png',
          'https://dpubstatic.udache.com/static/dpubimg/B6q1pWB0sB/cabin.png',
          'https://dpubstatic.udache.com/static/dpubimg/76n1ilzf4R/stone.png'
        ]
      }
    },
    mounted() {
      this.init()
    },
    beforeDestroy() {
      this.bs.destroy()
    },
    methods: {
      init() {
        this.bs = new BScroll(this.$refs.scroll, {
          observeImage: true
        })
      }
    }
  }
</script>
<style lang="stylus" rel="stylesheet/stylus" scoped>

.observe-image-container
  text-align center
  .scroll-wrapper
    position relative
    width 300px
    height 300px
    margin 20px auto
    border 3px solid #42b983
    border-radius 5px
    overflow hidden
  .scroll-content
    font-size 0
</style>

// packages/react-examples/src/pages/observe-image/components/default.js
import React, { useRef, useEffect } from 'react'
import BScroll from '@better-scroll/core'
import ObserveImage from '@better-scroll/observe-image'

BScroll.use(ObserveImage)

const images = [
  'https://dpubstatic.udache.com/static/dpubimg/dEswI1MVy6/zoo.png',
  'https://dpubstatic.udache.com/static/dpubimg/BYb_wPak21/home.png',
  'https://dpubstatic.udache.com/static/dpubimg/B6q1pWB0sB/cabin.png',
  'https://dpubstatic.udache.com/static/dpubimg/76n1ilzf4R/stone.png',
]

const Default = () => {
  const wrapperRef = useRef(null)
  const scrollRef = useRef(null)

  useEffect(() => {
    if (!scrollRef.current) {
      scrollRef.current = new BScroll(wrapperRef.current, {
        observeImage: true,
      })
    }
  }, [])

  return (
    <div className="observe-image-container view">
      <div className="scroll-wrapper" ref={wrapperRef}>
        <div className="scroll-content">
          {images.map((item, index) => (
            <img width="100%" src={item} alt="" key={index} />
          ))}
        </div>
      </div>
    </div>
  )
}

export default Default
