// example/vue/pages/slide/index.vue
<template>
  <div class="slide">
    <ul class="example-list">
      <li class="example-item" @click="goPage('/slide/banner')">
          <span>banner slider</span>
      </li>
      <li class="example-item" @click="goPage('/slide/fullpage')">
          <span>page slider</span>
      </li>
      <li class="example-item" @click="goPage('/slide/vertical')">
          <span>vertical slider</span>
      </li>
      <li class="example-item placeholder">
      </li>
    </ul>
    <transition name="move">
      <router-view class="view"></router-view>
    </transition>
  </div>
</template>
<script>
export default {
  methods: {
    goPage(path) {
      this.$router.push(path)
    }
  }
}
</script>
<style lang="stylus">
</style>

// packages/react-examples/src/pages/slide/index.js
import React from 'react'

import './index.styl'

const examples = [
  {
    path: '/slide/banner',
    name: 'banner slide',
  },
  {
    path: '/slide/fullpage',
    name: 'page slide',
  },
  {
    path: '/slide/vertical',
    name: 'vertical slide',
  },
]

const Core = (props) => {
  const goPage = (path) => {
    props.history.push(path)
  }

  return (
    <div className="view slide">
      <ul className="example-list">
        {examples.map((item) => (
          <li
            className="example-item"
            onClick={() => goPage(item.path)}
            key={item.path}
          >
            <span>{item.name}</span>
          </li>
        ))}
      </ul>
      {props.children}
    </div>
  )
}

export default Core
