// example/vue/components/picker/linkage-column.vue
<template>
  <div class="container">
    <ul class="example-list">
      <li class="example-item" @click="show">
          <span>{{selectedText}}</span>
      </li>
    </ul>
    <transition name="picker-fade">
      <div class="picker" v-show="state===1" @touchmove.prevent @click="_cancel">
        <transition name="picker-move">
          <div class="picker-panel" v-show="state===1" @click.stop>
            <div class="picker-choose border-bottom-1px">
              <span class="cancel" @click="_cancel">Cancel</span>
              <span class="confirm" @click="_confirm">Confirm</span>
              <h1 class="picker-title">Title</h1>
            </div>
            <div class="picker-content">
              <div class="mask-top border-bottom-1px"></div>
              <div class="mask-bottom border-top-1px"></div>
              <div class="wheel-wrapper" ref="wheelWrapper">
                <div class="wheel" v-for="(data, index) in pickerData" :key="index">
                  <ul class="wheel-scroll">
                    <li
                      v-for="item in data" :key="item.value"
                      :class="{'wheel-disabled-item':item.disabled}"
                      class="wheel-item">{{item.text}}</li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="picker-footer"></div>
          </div>
        </transition>
      </div>
    </transition>
  </div>
</template>

<script type="text/ecmascript-6">
  import BScroll from '@/index'
  import Wheel from '@/plugins/wheel'
  BScroll.use(Wheel)

  const STATE_HIDE = 0
  const STATE_SHOW = 1

  const COMPONENT_NAME = 'picker'
  const EVENT_SELECT = 'select'
  const EVENT_CANCEL = 'cancel'
  const EVENT_CHANGE = 'change'

  const DATA = [
    {
      text: '北京市',
      value: '110000',
      children: [
        {
          text: "北京市",
          value: '110100'
        }
      ]
    },
    {
      text: '天津市',
      value: '120000',
      children: [
        {
          text: "天津市",
          value: '120000'
        }
      ]
    },
    {
      text: '河北省',
      value: '130000',
      children: [
        {
          text: '石家庄市',
          value: '130100'
        },
        {
          text: '唐山市',
          value: '130200'
        },
        {
          text: '秦皇岛市',
          value: '130300'
        },
        {
          text: '邯郸市',
          value: '130400'
        },
        {
          text: '邢台市',
          value: '130500'
        },
        {
          text: '保定市',
          value: '130600'
        },
        {
          text: '张家口市',
          value: '130700'
        },
        {
          text: '承德市',
          value: '130800'
        }
      ]
    },
    {
      text: '山西省',
      value: '140000',
      children: [
        {
          text: '太原市',
          value: '140100'
        },
        {
          text: '大同市',
          value: '140200'
        },
        {
          text: '阳泉市',
          value: '140300'
        },
        {
          text: '长治市',
          value: '140400'
        },
        {
          text: '晋城市',
          value: '140500'
        },
        {
          text: '朔州市',
          value: '140600'
        },
        {
          text: '晋中市',
          value: '140700'
        }
      ]
    }
  ]

  export default {
    name: COMPONENT_NAME,
    data() {
      return {
        state: STATE_HIDE,
        selectedIndex: [0, 0],
        selectedText: 'open',
        pickerData: []
      }
    },
    created () {
      // generate data
      // like [[{text: 'province1', value: '1'}, {text: 'province2', value: '2'}], [{text: 'city1', value: '11'}, {text: 'city2', value: '22'}]
      // pickerData has two array, the first is province collections, second is city collections
      this._loadPickerData(this.selectedIndex, undefined /* no prevSelectedIndex due to instantiating */)
    },
    methods: {
      _loadPickerData (newSelectedIndex, oldSelectedIndex) {
        let provinces
        let cities
        // first instantiated
        if (!oldSelectedIndex) {
          provinces = DATA.map(({ value, text }) => ({ value, text }))
          cities = DATA[newSelectedIndex[0]].children
          this.pickerData = [provinces, cities]
        } else {
          // provinces'index changed, refresh cities data
          if (newSelectedIndex[0] !== oldSelectedIndex[0]) {
            cities = DATA[newSelectedIndex[0]].children
            this.pickerData.splice(1, 1, cities)
            // Since cities data changed
            // refresh better-scroll to recaculate scrollHeight
            this.$nextTick(() => {
              this.wheels[1].refresh()
            })
          }
        }
      },
      _confirm() {
        if (this._isMoving()) {
          return
        }
        this.hide()

        const currentSelectedIndex = this.selectedIndex = this.wheels.map(wheel => {
          return wheel.getSelectedIndex()
        })

        // store array for preventing multi-collecting array dependencies in Vue Source code
        const pickerData = this.pickerData
        const currentSelectedValue =
              this.selectedText =
                pickerData.map((data, index) => {
                  return data[currentSelectedIndex[index]].text
                }).join('-')
        this.$emit(EVENT_SELECT, currentSelectedIndex, currentSelectedValue)
      },
      _cancel() {
        this.hide()
        this.$emit(EVENT_CANCEL)
      },
      _isMoving() {
        return this.wheels.some((wheel) => {
          return wheel.pending
        })
      },
      show() {
        if (this.state === STATE_SHOW) {
          return
        }
        this.state = STATE_SHOW
        if (!this.wheels) {
          this.$nextTick(() => {
            this.wheels = []
            let wheelWrapper = this.$refs.wheelWrapper
            for (let i = 0; i < this.pickerData.length; i++) {
              this._createWheel(wheelWrapper, i)
            }
          })
        } else {
          for (let i = 0; i < this.pickerData.length; i++) {
            this.wheels[i].enable()
            this.wheels[i].wheelTo(this.selectedIndex[i])
          }
        }
      },
      hide() {
        this.state = STATE_HIDE

        for (let i = 0; i < this.pickerData.length; i++) {
          this.wheels[i].disable()
        }
      },
      refresh() {
        this.$nextTick(() => {
          this.wheels.forEach((wheel, index) => {
            wheel.refresh()
          })
        })
      },
      _createWheel(wheelWrapper, i) {
        const wheels = this.wheels
        if (!wheels[i]) {
          wheels[i] = new BScroll(wheelWrapper.children[i], {
            wheel: {
              selectedIndex: this.selectedIndex[i],
              wheelWrapperClass: 'wheel-scroll',
              wheelItemClass: 'wheel-item'
            },
            probeType: 3
          })
          // when any of wheels'scrolling ended , you should refresh data
          let prevSelectedIndex = this.selectedIndex
          wheels[i].on('scrollEnd', () => {
            const currentSelectedIndex = wheels.map(wheel => wheel.getSelectedIndex())
            this._loadPickerData(currentSelectedIndex, prevSelectedIndex)
            prevSelectedIndex = currentSelectedIndex
            this.$emit(EVENT_CHANGE, i, this.wheels[i].getSelectedIndex())
          })
        } else {
          this.wheels[i].refresh()
        }

        return this.wheels[i]
      },
      _diffSelectedIndex(newV, oldV) {

      }
    }
  }
</script>

<style scoped lang="stylus" rel="stylesheet/stylus">

  @import "~common/stylus/mixin.styl"
  @import "~common/stylus/variable.styl"

  .picker
    position: fixed
    left: 0
    top: 0
    z-index: 100
    width: 100%
    height: 100%
    overflow: hidden
    text-align: center
    font-size: $fontsize-medium
    background-color: $color-mask-bgc
    &.picker-fade-enter, &.picker-fade-leave-active
      opacity: 0
    &.picker-fade-enter-active, &.picker-fade-leave-active
      transition: all .3s ease-in-out

    .picker-panel
      position: absolute
      z-index: 600
      bottom: 0
      width: 100%
      height: 273px
      background: $color-white
      &.picker-move-enter, &.picker-move-leave-active
        transform: translate3d(0, 273px, 0)
      &.picker-move-enter-active, &.picker-move-leave-active
        transition: all .3s ease-in-out
      .picker-choose
        position: relative
        height: 60px
        color: $color-light-grey
        .picker-title
          margin: 0
          line-height: 60px
          font-weight: normal
          text-align: center
          font-size: $fontsize-large-x
          color: $color-dark-grey
        .confirm, .cancel
          position: absolute
          top: 6px
          padding: 16px
          font-size: $fontsize-medium
        .confirm
          right: 0
          color: $color-main
          &:active
            color: $color-main-ll
        .cancel
          left: 0
          &:active
            color: $color-active-light-gray-fe
      .picker-content
        position: relative
        top: 20px
        .mask-top, .mask-bottom
          z-index: 10
          width: 100%
          height: 68px
          pointer-events: none
          transform: translateZ(0)
        .mask-top
          position: absolute
          top: 0
          background: linear-gradient(to top, rgba(255, 255, 255, 0.4), rgba(255, 255, 255, 0.8))
        .mask-bottom
          position: absolute
          bottom: 1px
          background: linear-gradient(to bottom, rgba(255, 255, 255, 0.4), rgba(255, 255, 255, 0.8))
      .wheel-wrapper
        display: flex
        padding: 0 16px
        .wheel
          flex-fix()
          height: 173px
          overflow: hidden
          font-size: $fontsize-large-xx
          .wheel-scroll
            padding: 0
            margin-top: 68px
            line-height: 36px
            list-style: none
            .wheel-item
              list-style: none
              height: 36px
              overflow: hidden
              white-space: nowrap
              color: $color-dark-grey
              &.wheel-disabled-item
                opacity: .2;
    .picker-footer
      height: 20px
</style>

// packages/react-examples/src/pages/picker/components/linkage-column.js
import React, { useState, useRef, useEffect, useCallback } from 'react'
import { CSSTransition } from 'react-transition-group'
import BScroll from '@better-scroll/core'
import Wheel from '@better-scroll/wheel'

BScroll.use(Wheel)

const DATA = [
  {
    text: '北京市',
    value: '110000',
    children: [
      {
        text: '北京市',
        value: '110100',
      },
    ],
  },
  {
    text: '天津市',
    value: '120000',
    children: [
      {
        text: '天津市',
        value: '120000',
      },
    ],
  },
  {
    text: '河北省',
    value: '130000',
    children: [
      {
        text: '石家庄市',
        value: '130100',
      },
      {
        text: '唐山市',
        value: '130200',
      },
      {
        text: '秦皇岛市',
        value: '130300',
      },
      {
        text: '邯郸市',
        value: '130400',
      },
      {
        text: '邢台市',
        value: '130500',
      },
      {
        text: '保定市',
        value: '130600',
      },
      {
        text: '张家口市',
        value: '130700',
      },
      {
        text: '承德市',
        value: '130800',
      },
    ],
  },
  {
    text: '山西省',
    value: '140000',
    children: [
      {
        text: '太原市',
        value: '140100',
      },
      {
        text: '大同市',
        value: '140200',
      },
      {
        text: '阳泉市',
        value: '140300',
      },
      {
        text: '长治市',
        value: '140400',
      },
      {
        text: '晋城市',
        value: '140500',
      },
      {
        text: '朔州市',
        value: '140600',
      },
      {
        text: '晋中市',
        value: '140700',
      },
    ],
  },
]

const stopPropagation = (e) => {
  e.stopPropagation()
}

const preventDefault = (e) => {
  e.preventDefault()
}

const useStableCallback = (callback) => {
  const callbackRef = useRef(callback)

  useEffect(() => {
    callbackRef.current = callback
  })

  return useCallback((...args) => callbackRef.current(...args), [])
}

const LinkageColumn = () => {
  const [visible, setVisible] = useState(false)
  const [pickerData, setPickerData] = useState(() => [])
  const [selectedIndexPair, setSelectedIndexPair] = useState([0, 0])
  const [selectedText, setSelectedText] = useState('open')

  const wrapperRef = useRef(null)
  const scrollRef = useRef([])

  const loadPickerData = useStableCallback((newIndexPair, oldIndexPair) => {
    let provinces
    let cities
    // first instantiated
    if (!oldIndexPair) {
      provinces = DATA.map(({ value, text }) => ({ value, text }))
      cities = DATA[newIndexPair[0]].children
      setPickerData([provinces, cities])
    } else {
      // provinces'index changed, refresh cities data
      if (newIndexPair[0] !== oldIndexPair[0]) {
        cities = DATA[newIndexPair[0]].children.slice()
        setPickerData((prev) => {
          const next = [...prev]
          next.splice(1, 1, cities)
          return next
        })
        // Since cities data changed
        // refresh better-scroll to recaculate scrollHeight
        scrollRef.current[1].refresh()
      }
    }
  })

  const createWheels = useStableCallback(() => {
    const createWheel = (wheelWrapper, i) => {
      if (scrollRef.current[i]) {
        scrollRef.current[i].refresh()
      } else {
        const BS = (scrollRef.current[i] = new BScroll(
          wheelWrapper.children[i],
          {
            wheel: {
              wheelWrapperClass: 'wheel-scroll',
              wheelItemClass: 'wheel-item',
              selectedIndex: selectedIndexPair[i],
            },
            useTransition: false,
            probeType: 3,
          }
        ))

        // when any of wheels'scrolling ended , refresh data
        let prevSelectedIndexPair = selectedIndexPair
        BS.on('scrollEnd', () => {
          const currentSelectedIndexPair = scrollRef.current.map((wheel) =>
            wheel.getSelectedIndex()
          )
          loadPickerData(currentSelectedIndexPair, prevSelectedIndexPair)
          prevSelectedIndexPair = currentSelectedIndexPair
        })
      }
    }

    const wrapper = wrapperRef.current
    for (let i = 0; i < pickerData.length; i++) {
      createWheel(wrapper, i)
    }
  })

  useEffect(() => {
    loadPickerData(selectedIndexPair)
  }, [loadPickerData, selectedIndexPair])

  useEffect(() => {
    if (visible) {
      createWheels()
    }
  }, [visible, createWheels])

  const handleShow = () => {
    if (visible) {
      return
    }
    setVisible(true)
  }

  const handleHide = () => {
    setVisible(false)
  }

  const handleConfirm = () => {
    scrollRef.current.forEach((wheel) => {
      /*
       * if bs is scrolling, force it stop at the nearest wheel-item
       * or you can use 'restorePosition' method as the below
       */
      // wheel.stop()
      /*
       * if bs is scrolling, restore it to the start position
       * it is same with iOS picker and web Select element implementation
       * supported at v2.1.0
       */
      wheel.restorePosition()
    })
    handleHide()
    const currentSelectedIndexPair = scrollRef.current.map((wheel) =>
      wheel.getSelectedIndex()
    )
    setSelectedIndexPair(currentSelectedIndexPair)
    setSelectedText(
      pickerData
        .map((data, i) => {
          const index = currentSelectedIndexPair[i]
          return `${data[index].text}-${index}`
        })
        .join('__')
    )
  }

  const handleCancel = () => {
    /*
     * if bs is scrolling, restore it to the start position
     * it is same with iOS picker and web Select element implementation
     * supported at v2.1.0
     */
    scrollRef.current.forEach((wheel) => {
      wheel.restorePosition()
    })
    handleHide()
  }

  return (
    <div className="container view">
      <div className="container-btn" onClick={handleShow}>
        {selectedText}
      </div>
      <CSSTransition
        in={visible}
        classNames="picker-fade"
        timeout={300}
        onEnter={(node) => {
          node.style.display = 'block'
        }}
        onExited={(node) => {
          node.style.display = ''
        }}
      >
        <div
          className="picker"
          onClick={handleCancel}
          onTouchMove={preventDefault}
        >
          <CSSTransition in={visible} classNames="picker-move" timeout={300}>
            <div className="picker-panel" onClick={stopPropagation}>
              <div className="picker-choose border-bottom-1px">
                <span className="cancel" onClick={handleCancel}>
                  Cancel
                </span>
                <span className="confirm" onClick={handleConfirm}>
                  Confirm
                </span>
                <h1 className="picker-title">Title</h1>
              </div>
              <div className="picker-content">
                <div className="mask-top border-bottom-1px"></div>
                <div className="mask-bottom border-top-1px"></div>
                <div className="wheel-wrapper" ref={wrapperRef}>
                  {pickerData.map((data, index) => (
                    <div className="wheel" key={index}>
                      <ul className="wheel-scroll">
                        {data.map((item) => (
                          <li key={item.value} className="wheel-item">
                            {item.text}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
              <div className="picker-footer"></div>
            </div>
          </CSSTransition>
        </div>
      </CSSTransition>
    </div>
  )
}

export default LinkageColumn
