// packages/react-examples/src/pages/scrollbar/components/vertical.js
import React, { useRef, useEffect } from 'react'
import BScroll from '@better-scroll/core'
import ScrollBar from '@better-scroll/scroll-bar'

BScroll.use(ScrollBar)

const createArray = (length) => Array.from({ length }, (_v, i) => i + 1)
const data = createArray(40)

const Vertical = () => {
  const wrapperRef = useRef(null)
  const scrollRef = useRef(null)

  useEffect(() => {
    if (!scrollRef.current) {
      scrollRef.current = new BScroll(wrapperRef.current, {
        scrollY: true,
        scrollbar: true,
      })
    }
  }, [])

  return (
    <div className="scrollbar view">
      <div className="scrollbar-wrapper" ref={wrapperRef}>
        <div className="scrollbar-content">
          {data.map((item) => (
            <div key={item} className="scrollbar-content-item">
              {`I am item ${item} `}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default Vertical

// packages/examples/vue/components/scrollbar/vertical.vue
<template>
  <div class="scrollbar">
    <div ref="wrapper" class="scrollbar-wrapper">
      <ul class="scrollbar-content">
        <li v-for="i of 40" :key="i" class="scrollbar-content-item">
          {{ `I am item ${i} `}}
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
  import BScroll from '@better-scroll/core'
  import ScrollBar from '@better-scroll/scroll-bar'

  BScroll.use(ScrollBar)

  export default {
    mounted() {
      this.initBscroll()
    },
    methods: {
      initBscroll() {
        this.scroll = new BScroll(this.$refs.wrapper, {
          scrollY: true,
          scrollbar: true
        })
      }
    }
  }
</script>

<style lang="stylus">
.scrollbar
  height: 100%
.scrollbar-wrapper
  position: relative
  height: 100%
  padding: 0 10px
  border: 1px solid #ccc
  overflow: hidden
.scrollbar-content-item
  padding: 10px 0
  list-style: none
  border-bottom: 1px solid #ccc
  text-align: left
</style>
