// packages/react-examples/src/pages/mouse-wheel/components/pullup.js
import React, { useState, useRef, useEffect, useCallback } from 'react'
import BScroll from '@better-scroll/core'
import Pullup from '@better-scroll/pull-up'
import MouseWheel from '@better-scroll/mouse-wheel'

BScroll.use(Pullup)
BScroll.use(MouseWheel)

const createArray = (length) => Array.from({ length }, (_v, i) => i + 1)

const useStableCallback = (callback) => {
  const callbackRef = useRef(callback)

  useEffect(() => {
    callbackRef.current = callback
  })

  return useCallback((...args) => callbackRef.current(...args), [])
}

const ajaxGet = (/* url */) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(20)
    }, 1000)
  })
}

const PullupPage = () => {
  const [isPullUpLoad, setIsPullUpLoad] = useState(false)
  const [num, setNum] = useState(30)

  const wrapperRef = useRef(null)
  const scrollRef = useRef(null)

  const requestData = async () => {
    try {
      const newData = await ajaxGet(/* url */)
      setNum((n) => n + newData)
    } catch (err) {
      // handle err
      console.log(err)
    }
  }

  const pullingUpHandler = useStableCallback(async () => {
    setIsPullUpLoad(true)
    await requestData()
    scrollRef.current.finishPullUp()
    scrollRef.current.refresh()
    setIsPullUpLoad(false)
  })

  useEffect(() => {
    if (!scrollRef.current) {
      const BS = (scrollRef.current = new BScroll(wrapperRef.current, {
        probeType: 3,
        pullUpLoad: true,
        mouseWheel: true,
      }))

      BS.on('pullingUp', pullingUpHandler)
    }
  }, [pullingUpHandler])

  return (
    <div className="mouse-wheel-pullup view">
      <div className="pullup-wrapper" ref={wrapperRef}>
        <div className="pullup-content">
          <ul className="pullup-list">
            {createArray(num).map((item, index) => (
              <li key={index} className="pullup-list-item">
                {item % 5 === 0 ? 'scroll up 👆🏻' : `I am item ${item} `}
              </li>
            ))}
          </ul>
          <div className="pullup-tips">
            {isPullUpLoad ? (
              <div className="after-trigger">
                <span className="pullup-txt">Loading...</span>
              </div>
            ) : (
              <div className="before-trigger">
                <span className="pullup-txt">Pull up and load more</span>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

export default PullupPage

// packages/examples/vue/components/mouse-wheel/pullup.vue
<template>
  <div class="mouse-wheel-pullup">
    <div ref="scroll" class="pullup-wrapper">
      <div class="pullup-content">
        <ul class="pullup-list">
          <li v-for="i of data" :key="i" class="pullup-list-item">
            {{ i % 5 === 0 ? 'use your mousewheel please 👆🏻' : `I am item ${i} `}}
          </li>
        </ul>
        <div class="pullup-tips">
          <div v-if="!isPullUpLoad" class="before-trigger">
            <span class="pullup-txt">mousewheel trigger pullingup and load more</span>
          </div>
          <div v-else class="after-trigger">
            <span class="pullup-txt">Loading...</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import BScroll from '@better-scroll/core'
  import Pullup from '@better-scroll/pull-up'
  import MouseWheel from '@better-scroll/mouse-wheel'

  BScroll.use(Pullup)
  BScroll.use(MouseWheel)

  export default {
    data() {
      return {
        isPullUpLoad: false,
        data: 30
      }
    },
    mounted() {
      this.initBscroll()
    },
    methods: {
      initBscroll() {
        this.scroll = new BScroll(this.$refs.scroll, {
          probeType: 3,
          pullUpLoad: true,
          mouseWheel: true
        })

        this.scroll.on('pullingUp', this.pullingUpHandler)
      },
      async pullingUpHandler() {
        this.isPullUpLoad = true

        await this.requestData()

        this.scroll.finishPullUp()
        this.scroll.refresh()
        this.isPullUpLoad = false
      },
      async requestData() {
        try {
          const newData = await this.ajaxGet(/* url */)
          this.data += newData
        } catch (err) {
          // handle err
          console.log(err)
        }
      },
      ajaxGet(/* url */) {
        return new Promise(resolve => {
          setTimeout(() => {
            resolve(20)
          }, 1000)
        })
      }
    }
  }
</script>

<style lang="stylus" scoped>
.mouse-wheel-pullup
  height: 100%
  .pullup-wrapper
    height: 100%
    padding: 0 10px
    border: 1px solid #ccc
    overflow: hidden
  .pullup-list
    padding: 0
  .pullup-list-item
    padding: 10px 0
    list-style: none
    border-bottom: 1px solid #ccc
  .pullup-tips
    padding: 20px
    text-align: center
    color: #999
</style>
