// packages/react-examples/src/pages/mouse-wheel/components/pulldown.js
import React, { useState, useRef, useEffect, useCallback } from 'react'
import BScroll from '@better-scroll/core'
import PullDown from '@better-scroll/pull-down'
import MouseWheel from '@better-scroll/mouse-wheel'

BScroll.use(PullDown)
BScroll.use(MouseWheel)

const useStableCallback = (callback) => {
  const callbackRef = useRef(callback)

  useEffect(() => {
    callbackRef.current = callback
  })

  return useCallback((...args) => callbackRef.current(...args), [])
}

const ajaxGet = (/* url */) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const dataList = generateData()
      resolve(dataList)
    }, 1000)
  })
}

const TIME_BOUNCE = 800
let STEP = 0

function generateData() {
  const BASE = 30
  const begin = BASE * STEP
  const end = BASE * (STEP + 1)
  let ret = []
  for (let i = end; i > begin; i--) {
    ret.push(i)
  }
  return ret
}

const Pulldown = () => {
  const [beforePullDown, setBeforePullDown] = useState(true)
  const [isPullingDown, setIsPullingDown] = useState(false)
  const [data, setData] = useState(generateData())

  const wrapperRef = useRef(null)
  const scrollRef = useRef(null)

  const requestData = async () => {
    try {
      const newData = await ajaxGet(/* url */)
      setData((prev) => newData.concat(prev))
    } catch (err) {
      // handle err
      console.log(err)
    }
  }

  const finishPullDown = () => {
    scrollRef.current.finishPullDown()
    setTimeout(() => {
      setBeforePullDown(true)
      scrollRef.current.refresh()
    }, TIME_BOUNCE + 100)
  }

  const pullingDownHandler = useStableCallback(async () => {
    setBeforePullDown(false)
    setIsPullingDown(true)
    STEP += 1
    await requestData()
    setIsPullingDown(false)
    finishPullDown()
  })

  useEffect(() => {
    if (!scrollRef.current) {
      const BS = (scrollRef.current = new BScroll(wrapperRef.current, {
        scrollY: true,
        bounceTime: TIME_BOUNCE,
        pullDownRefresh: {
          threshold: 70,
          stop: 56,
        },
        mouseWheel: true,
      }))

      BS.on('pullingDown', pullingDownHandler)

      BS.on('scroll', (pos) => {
        console.log(pos.y)
      })

      BS.on('scrollEnd', () => {
        console.log('scrollEnd')
      })
    }
  }, [pullingDownHandler])

  return (
    <div className="mouse-wheel-pulldown view">
      <div className="pulldown-wrapper" ref={wrapperRef}>
        <div className="pulldown-content">
          <div className="pulldown-tips">
            <div style={{ display: beforePullDown ? '' : 'none' }}>
              <span>Pull Down and refresh</span>
            </div>
            <div style={{ display: beforePullDown ? 'none' : '' }}>
              <div v-show="isPullingDown">
                <span>Loading...</span>
              </div>
              <div style={{ display: isPullingDown ? 'none' : '' }}>
                <span>Refresh success</span>
              </div>
            </div>
          </div>
          <ul className="pulldown-list">
            {data.map((item, index) => (
              <li key={index} className="pulldown-list-item">
                {`I am item ${item} `}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}

export default Pulldown

// packages/examples/vue/components/mouse-wheel/pulldown.vue
<template>
  <div class="mouse-wheel-pulldown">
    <div ref="scroll" class="pulldown-wrapper">
      <div class="pulldown-content">
        <div class="pulldown-tips">
          <div v-show="beforePullDown">
            <span>Pull Down and refresh</span>
          </div>
          <div v-show="!beforePullDown">
            <div v-show="isPullingDown">
              <span>Loading...</span>
            </div>
            <div v-show="!isPullingDown"><span>Refresh success</span></div>
          </div>
        </div>
        <ul class="pulldown-list">
          <li v-for="i of dataList" :key="i" class="pulldown-list-item">
            {{ `I am item ${i} ` }}
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script>
  import BScroll from '@better-scroll/core'
  import PullDown from '@better-scroll/pull-down'
  import MouseWheel from '@better-scroll/mouse-wheel'

  BScroll.use(PullDown)
  BScroll.use(MouseWheel)

  function generateData() {
    const BASE = 30
    const begin = BASE * STEP
    const end = BASE * (STEP + 1)
    let ret = []
    for(let i = end; i > begin; i--) {
      ret.push(i)
    }
    return ret
  }

  const TIME_BOUNCE = 800
  const TIME_STOP = 600
  const REQUEST_TIME = 1000
  const THRESHOLD = 70
  const STOP = 56
  let STEP = 0

  export default {
    data() {
      return {
        beforePullDown: true,
        isPullingDown: false,
        dataList: generateData()
      }
    },
    mounted() {
      this.initBscroll()
    },
    methods: {
      initBscroll() {
        this.bscroll = new BScroll(this.$refs.scroll, {
          scrollY: true,
          bounceTime: TIME_BOUNCE,
          mouseWheel: true,
          pullDownRefresh: {
            threshold: THRESHOLD,
            stop: STOP
          }
        })

        this.bscroll.on('pullingDown', this.pullingDownHandler)
        this.bscroll.on('scroll', this.scrollHandler)
        this.bscroll.on('scrollEnd', (e) => {
          console.log('scrollEnd')
        })
      },
      scrollHandler(pos) {
        console.log(pos.y)
      },
      async pullingDownHandler() {
        console.log('trigger pullDown')
        this.beforePullDown = false
        this.isPullingDown = true
        STEP += 1

        await this.requestData()

        this.isPullingDown = false
        this.finishPullDown()
      },
      async finishPullDown() {
        const stopTime = TIME_STOP
        await new Promise(resolve => {
          setTimeout(() => {
            this.bscroll.finishPullDown()
            resolve()
          }, stopTime)
        })
        setTimeout(() => {
          this.beforePullDown = true
          this.bscroll.refresh()
        }, TIME_BOUNCE)
      },
      async requestData() {
        try {
          const newData = await this.ajaxGet(/* url */)
          this.dataList = newData.concat(this.dataList)
        } catch (err) {
          // handle err
          console.log(err)
        }
      },
      ajaxGet(/* url */) {
        return new Promise(resolve => {
          setTimeout(() => {
            const dataList = generateData()
            resolve(dataList)
          }, REQUEST_TIME)
        })
      }
    }
  }
</script>

<style lang="stylus" scoped>
.mouse-wheel-pulldown
  height: 100%
  .pulldown-wrapper
    position: relative
    height: 100%
    padding: 0 10px
    border: 1px solid #ccc
    overflow: hidden
  .pulldown-list
    padding: 0
  .pulldown-list-item
    padding: 10px 0
    list-style: none
    border-bottom: 1px solid #ccc
  .pulldown-tips
    position: absolute
    width: 100%
    padding: 20px
    box-sizing: border-box
    transform: translateY(-100%) translateZ(0)
    text-align: center
    color: #999
</style>
