// example/vue/pages/core/index.vue
<template>
  <div class="core">
    <ul class="example-list">
      <li class="example-item" @click="goPage('/core/mouse-wheel')">
          <span>mouse wheel</span>
      </li>
      <li class="example-item placeholder">
      </li>
    </ul>
    <transition name="move">
      <router-view class="view"></router-view>
    </transition>
  </div>
</template>
<script>
export default {
  methods: {
    goPage(path) {
      this.$router.push(path)
    }
  }
}
</script>

// packages/examples/react/pages/core/index.jsx
import React from 'react'

import './index.styl'

const Core = (props) => {
  const goPage = (path) => {
    props.history.push(path)
  }

  return (
    <div className="view core">
      <ul className="example-list">
        <li className="example-item" onClick={() => goPage('/core/default')}>
          <span>vertical</span>
        </li>
        <li className="example-item" onClick={() => goPage('/core/horizontal')}>
          <span>horizontal</span>
        </li>
        <li
          className="example-item"
          onClick={() => goPage('/core/dynamic-content')}
        >
          <span>dynamic-content</span>
        </li>
        <li
          className="example-item"
          onClick={() => goPage('/core/specified-content')}
        >
          <span>specified-content</span>
        </li>
        <li className="example-item" onClick={() => goPage('/core/freescroll')}>
          <span>freescroll</span>
        </li>
      </ul>
      {props.children}
    </div>
  )
}

export default Core
